// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_model_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_model_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_model_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_model_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_model_2eproto;
namespace anx {
class ModelMeta;
struct ModelMetaDefaultTypeInternal;
extern ModelMetaDefaultTypeInternal _ModelMeta_default_instance_;
}  // namespace anx
PROTOBUF_NAMESPACE_OPEN
template <>
::anx::ModelMeta* Arena::CreateMaybeMessage<::anx::ModelMeta>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace anx {

// ===================================================================


// -------------------------------------------------------------------

class ModelMeta final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:anx.ModelMeta) */ {
 public:
  inline ModelMeta() : ModelMeta(nullptr) {}
  ~ModelMeta() override;
  explicit PROTOBUF_CONSTEXPR ModelMeta(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ModelMeta(const ModelMeta& from);
  ModelMeta(ModelMeta&& from) noexcept
    : ModelMeta() {
    *this = ::std::move(from);
  }

  inline ModelMeta& operator=(const ModelMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModelMeta& operator=(ModelMeta&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModelMeta& default_instance() {
    return *internal_default_instance();
  }
  static inline const ModelMeta* internal_default_instance() {
    return reinterpret_cast<const ModelMeta*>(
               &_ModelMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ModelMeta& a, ModelMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(ModelMeta* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModelMeta* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModelMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ModelMeta>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ModelMeta& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ModelMeta& from) {
    ModelMeta::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModelMeta* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "anx.ModelMeta";
  }
  protected:
  explicit ModelMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInputDimsFieldNumber = 1,
    kOutputDimsFieldNumber = 3,
    kInputDtypeFieldNumber = 2,
    kOutputDtypeFieldNumber = 4,
  };
  // repeated int32 input_dims = 1;
  int input_dims_size() const;
  private:
  int _internal_input_dims_size() const;

  public:
  void clear_input_dims() ;
  ::int32_t input_dims(int index) const;
  void set_input_dims(int index, ::int32_t value);
  void add_input_dims(::int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& input_dims() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* mutable_input_dims();

  private:
  ::int32_t _internal_input_dims(int index) const;
  void _internal_add_input_dims(::int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& _internal_input_dims() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* _internal_mutable_input_dims();

  public:
  // repeated int32 output_dims = 3;
  int output_dims_size() const;
  private:
  int _internal_output_dims_size() const;

  public:
  void clear_output_dims() ;
  ::int32_t output_dims(int index) const;
  void set_output_dims(int index, ::int32_t value);
  void add_output_dims(::int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& output_dims() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* mutable_output_dims();

  private:
  ::int32_t _internal_output_dims(int index) const;
  void _internal_add_output_dims(::int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& _internal_output_dims() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* _internal_mutable_output_dims();

  public:
  // uint32 input_dtype = 2;
  void clear_input_dtype() ;
  ::uint32_t input_dtype() const;
  void set_input_dtype(::uint32_t value);

  private:
  ::uint32_t _internal_input_dtype() const;
  void _internal_set_input_dtype(::uint32_t value);

  public:
  // uint32 output_dtype = 4;
  void clear_output_dtype() ;
  ::uint32_t output_dtype() const;
  void set_output_dtype(::uint32_t value);

  private:
  ::uint32_t _internal_output_dtype() const;
  void _internal_set_output_dtype(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:anx.ModelMeta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t> input_dims_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _input_dims_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t> output_dims_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _output_dims_cached_byte_size_;
    ::uint32_t input_dtype_;
    ::uint32_t output_dtype_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_model_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ModelMeta

// repeated int32 input_dims = 1;
inline int ModelMeta::_internal_input_dims_size() const {
  return _impl_.input_dims_.size();
}
inline int ModelMeta::input_dims_size() const {
  return _internal_input_dims_size();
}
inline void ModelMeta::clear_input_dims() {
  _impl_.input_dims_.Clear();
}
inline ::int32_t ModelMeta::input_dims(int index) const {
  // @@protoc_insertion_point(field_get:anx.ModelMeta.input_dims)
  return _internal_input_dims(index);
}
inline void ModelMeta::set_input_dims(int index, ::int32_t value) {
  _impl_.input_dims_.Set(index, value);
  // @@protoc_insertion_point(field_set:anx.ModelMeta.input_dims)
}
inline void ModelMeta::add_input_dims(::int32_t value) {
  _internal_add_input_dims(value);
  // @@protoc_insertion_point(field_add:anx.ModelMeta.input_dims)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& ModelMeta::input_dims() const {
  // @@protoc_insertion_point(field_list:anx.ModelMeta.input_dims)
  return _internal_input_dims();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* ModelMeta::mutable_input_dims() {
  // @@protoc_insertion_point(field_mutable_list:anx.ModelMeta.input_dims)
  return _internal_mutable_input_dims();
}

inline ::int32_t ModelMeta::_internal_input_dims(int index) const {
  return _impl_.input_dims_.Get(index);
}
inline void ModelMeta::_internal_add_input_dims(::int32_t value) { _impl_.input_dims_.Add(value); }
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& ModelMeta::_internal_input_dims() const {
  return _impl_.input_dims_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* ModelMeta::_internal_mutable_input_dims() {
  return &_impl_.input_dims_;
}

// uint32 input_dtype = 2;
inline void ModelMeta::clear_input_dtype() {
  _impl_.input_dtype_ = 0u;
}
inline ::uint32_t ModelMeta::input_dtype() const {
  // @@protoc_insertion_point(field_get:anx.ModelMeta.input_dtype)
  return _internal_input_dtype();
}
inline void ModelMeta::set_input_dtype(::uint32_t value) {
  _internal_set_input_dtype(value);
  // @@protoc_insertion_point(field_set:anx.ModelMeta.input_dtype)
}
inline ::uint32_t ModelMeta::_internal_input_dtype() const {
  return _impl_.input_dtype_;
}
inline void ModelMeta::_internal_set_input_dtype(::uint32_t value) {
  ;
  _impl_.input_dtype_ = value;
}

// repeated int32 output_dims = 3;
inline int ModelMeta::_internal_output_dims_size() const {
  return _impl_.output_dims_.size();
}
inline int ModelMeta::output_dims_size() const {
  return _internal_output_dims_size();
}
inline void ModelMeta::clear_output_dims() {
  _impl_.output_dims_.Clear();
}
inline ::int32_t ModelMeta::output_dims(int index) const {
  // @@protoc_insertion_point(field_get:anx.ModelMeta.output_dims)
  return _internal_output_dims(index);
}
inline void ModelMeta::set_output_dims(int index, ::int32_t value) {
  _impl_.output_dims_.Set(index, value);
  // @@protoc_insertion_point(field_set:anx.ModelMeta.output_dims)
}
inline void ModelMeta::add_output_dims(::int32_t value) {
  _internal_add_output_dims(value);
  // @@protoc_insertion_point(field_add:anx.ModelMeta.output_dims)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& ModelMeta::output_dims() const {
  // @@protoc_insertion_point(field_list:anx.ModelMeta.output_dims)
  return _internal_output_dims();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* ModelMeta::mutable_output_dims() {
  // @@protoc_insertion_point(field_mutable_list:anx.ModelMeta.output_dims)
  return _internal_mutable_output_dims();
}

inline ::int32_t ModelMeta::_internal_output_dims(int index) const {
  return _impl_.output_dims_.Get(index);
}
inline void ModelMeta::_internal_add_output_dims(::int32_t value) { _impl_.output_dims_.Add(value); }
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& ModelMeta::_internal_output_dims() const {
  return _impl_.output_dims_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* ModelMeta::_internal_mutable_output_dims() {
  return &_impl_.output_dims_;
}

// uint32 output_dtype = 4;
inline void ModelMeta::clear_output_dtype() {
  _impl_.output_dtype_ = 0u;
}
inline ::uint32_t ModelMeta::output_dtype() const {
  // @@protoc_insertion_point(field_get:anx.ModelMeta.output_dtype)
  return _internal_output_dtype();
}
inline void ModelMeta::set_output_dtype(::uint32_t value) {
  _internal_set_output_dtype(value);
  // @@protoc_insertion_point(field_set:anx.ModelMeta.output_dtype)
}
inline ::uint32_t ModelMeta::_internal_output_dtype() const {
  return _impl_.output_dtype_;
}
inline void ModelMeta::_internal_set_output_dtype(::uint32_t value) {
  ;
  _impl_.output_dtype_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace anx


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_model_2eproto_2epb_2eh
