# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: assets.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61ssets.proto\x12\x03\x61nx\x1a\x0c\x63ommon.proto\"}\n\nAssetState\x12!\n\x03imu\x18\x01 \x01(\x0b\x32\x14.anx.DeviceImuSelect\x12#\n\x04gnss\x18\x02 \x01(\x0b\x32\x15.anx.DeviceGnssSelect\x12\'\n\x06\x63\x61mera\x18\x03 \x01(\x0b\x32\x17.anx.DeviceCameraSelect\"\x1e\n\x0f\x44\x65viceImuSelect\x12\x0b\n\x03\x66ps\x18\x01 \x03(\r\"%\n\x10\x44\x65viceGnssSelect\x12\x11\n\tavailable\x18\x01 \x01(\x08\"E\n\x12\x44\x65viceCameraSelect\x12/\n\x0e\x63\x61mera_streams\x18\x01 \x03(\x0b\x32\x17.anx.DeviceCameraStream\"\xa1\x01\n\x12\x44\x65viceCameraStream\x12\x0b\n\x03\x66ps\x18\x01 \x01(\r\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x39\n\x0cpixel_format\x18\x04 \x01(\x0e\x32#.anx.DeviceCameraStream.PixelFormat\"$\n\x0bPixelFormat\x12\t\n\x05MJPEG\x10\x00\x12\n\n\x06YUV420\x10\x01\"\x1d\n\x0eStartDeviceImu\x12\x0b\n\x03\x66ps\x18\x01 \x01(\r\"C\n\x11StartDeviceCamera\x12.\n\rcamera_stream\x18\x01 \x01(\x0b\x32\x17.anx.DeviceCameraStream\"\xd8\x02\n\x07ImuData\x12\'\n\x08\x66iltered\x18\x01 \x01(\x0b\x32\x15.anx.ImuData.Filtered\x12\x1d\n\x03raw\x18\x02 \x01(\x0b\x32\x10.anx.ImuData.Raw\x1a|\n\x08\x46iltered\x12\"\n\x0c\x61\x63\x63\x65leration\x18\x01 \x01(\x0b\x32\x0c.anx.Vector3\x12&\n\x10\x61ngular_velocity\x18\x02 \x01(\x0b\x32\x0c.anx.Vector3\x12$\n\x0borientation\x18\x03 \x01(\x0b\x32\x0f.anx.Quaternion\x1a\x86\x01\n\x03Raw\x12\"\n\x0c\x61\x63\x63\x65leration\x18\x01 \x01(\x0b\x32\x0c.anx.Vector3\x12&\n\x10\x61ngular_velocity\x18\x02 \x01(\x0b\x32\x0c.anx.Vector3\x12\x33\n\x1dmagnetic_field_in_micro_tesla\x18\x03 \x01(\x0b\x32\x0c.anx.Vector3\"\x18\n\x08GnssData\x12\x0c\n\x04nmea\x18\x01 \x01(\t\"\x1b\n\nCameraData\x12\r\n\x05image\x18\x01 \x01(\x0c\x42\x1b\n\x19\x63om.flomobility.anx.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assets_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031com.flomobility.anx.proto'
  _globals['_ASSETSTATE']._serialized_start=35
  _globals['_ASSETSTATE']._serialized_end=160
  _globals['_DEVICEIMUSELECT']._serialized_start=162
  _globals['_DEVICEIMUSELECT']._serialized_end=192
  _globals['_DEVICEGNSSSELECT']._serialized_start=194
  _globals['_DEVICEGNSSSELECT']._serialized_end=231
  _globals['_DEVICECAMERASELECT']._serialized_start=233
  _globals['_DEVICECAMERASELECT']._serialized_end=302
  _globals['_DEVICECAMERASTREAM']._serialized_start=305
  _globals['_DEVICECAMERASTREAM']._serialized_end=466
  _globals['_DEVICECAMERASTREAM_PIXELFORMAT']._serialized_start=430
  _globals['_DEVICECAMERASTREAM_PIXELFORMAT']._serialized_end=466
  _globals['_STARTDEVICEIMU']._serialized_start=468
  _globals['_STARTDEVICEIMU']._serialized_end=497
  _globals['_STARTDEVICECAMERA']._serialized_start=499
  _globals['_STARTDEVICECAMERA']._serialized_end=566
  _globals['_IMUDATA']._serialized_start=569
  _globals['_IMUDATA']._serialized_end=913
  _globals['_IMUDATA_FILTERED']._serialized_start=652
  _globals['_IMUDATA_FILTERED']._serialized_end=776
  _globals['_IMUDATA_RAW']._serialized_start=779
  _globals['_IMUDATA_RAW']._serialized_end=913
  _globals['_GNSSDATA']._serialized_start=915
  _globals['_GNSSDATA']._serialized_end=939
  _globals['_CAMERADATA']._serialized_start=941
  _globals['_CAMERADATA']._serialized_end=968
# @@protoc_insertion_point(module_scope)