# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x03\x61nx\"/\n\x0bStdResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1a\n\x07Payload\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"\x07\n\x05\x45mptyB\x1b\n\x19\x63om.flomobility.anx.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031com.flomobility.anx.proto'
  _globals['_STDRESPONSE']._serialized_start=21
  _globals['_STDRESPONSE']._serialized_end=68
  _globals['_PAYLOAD']._serialized_start=70
  _globals['_PAYLOAD']._serialized_end=96
  _globals['_VECTOR3']._serialized_start=98
  _globals['_VECTOR3']._serialized_end=140
  _globals['_QUATERNION']._serialized_start=142
  _globals['_QUATERNION']._serialized_end=198
  _globals['_EMPTY']._serialized_start=200
  _globals['_EMPTY']._serialized_end=207
# @@protoc_insertion_point(module_scope)