# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x03\x61nx\"\'\n\x16GetImeiNumbersResponse\x12\r\n\x05imeis\x18\x01 \x03(\t\"0\n\x0eSetWifiRequest\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\xce\x01\n\tDeviceLog\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x0b\n\x03tid\x18\x02 \x01(\r\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12#\n\x05level\x18\x04 \x01(\x0e\x32\x14.anx.DeviceLog.Level\x12\x0b\n\x03tag\x18\x05 \x01(\t\x12\x0b\n\x03msg\x18\x06 \x01(\t\"U\n\x05Level\x12\x0b\n\x07VERBOSE\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x08\n\x04INFO\x10\x03\x12\x08\n\x04WARN\x10\x04\x12\t\n\x05\x46\x41TAL\x10\x05\x12\n\n\x06SILENT\x10\x06\"\"\n\x0fVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\tB\x1b\n\x19\x63om.flomobility.anx.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031com.flomobility.anx.proto'
  _globals['_GETIMEINUMBERSRESPONSE']._serialized_start=21
  _globals['_GETIMEINUMBERSRESPONSE']._serialized_end=60
  _globals['_SETWIFIREQUEST']._serialized_start=62
  _globals['_SETWIFIREQUEST']._serialized_end=110
  _globals['_DEVICELOG']._serialized_start=113
  _globals['_DEVICELOG']._serialized_end=319
  _globals['_DEVICELOG_LEVEL']._serialized_start=234
  _globals['_DEVICELOG_LEVEL']._serialized_end=319
  _globals['_VERSIONRESPONSE']._serialized_start=321
  _globals['_VERSIONRESPONSE']._serialized_end=355
# @@protoc_insertion_point(module_scope)